### ISSUE TITLE
error on execute

### ISSUE THREAD

**Issue by skiweather** [beaubellamy/SkiResortScraper#1]
File "C:\ProgramData\Anaconda3\lib\site-packages\bs4\__init__.py", line 192, in __init__
    elif len(markup) <= 256 and (

TypeError: object of type 'NoneType' has no len()

**Comment by beaubellamy** [comment]
Error seemed only to appear when scraping through a firewall.
Correcting the base url to a secure url "https//...." appears to correct the error.
